#!/usr/bin/python3
#
# (C) Copyright 2019-2020 CERN
#
# This  software  is  distributed  under  the  terms  of  the  GNU  General  Public  Licence  version  3
# (GPL  Version 3), copied verbatim in the file "COPYING" /copied verbatim below.
#
# In applying this licence, CERN does not waive the privileges and immunities granted to it
# by virtue of its status as an Intergovernmental Organization or submit itself to any jurisdiction.
#
'''Acron file backend credentials setter'''

import argparse
import os
import shutil
import sys
import pkg_resources
import yaml
from acron.constants import ReturnCodes
from acron.exceptions import GPGError, KlistError, KinitError
from acron.utils import gpg_decrypt_file, krb_check_keytab, krb_init_keytab

with open('/etc/acron/server.config', 'r') as config_file:
    CONFIG = yaml.safe_load(config_file)
with open(os.path.join(CONFIG['CREDS']['CONFIG'], 'file.config'), 'r') as config_file:
    CONFIG['CREDS'].update(yaml.safe_load(config_file))

__author__ = 'Philippe Ganz (CERN)'
__credits__ = ['Philippe Ganz (CERN)', 'Ulrich Schwickerath (CERN)',
               'Rodrigo Bermudez Schettino (CERN)']
__maintainer__ = 'Rodrigo Bermudez Schettino (CERN)'
__email__ = 'rodrigo.bermudez.schettino@cern.ch'
__status__ = 'Development'


def store_creds(username, creds_file_encrypted):
    '''
    Store the credentials on the shared file system.

    :param username:         user to store the credentials for
    :param creds_file_encrypted: location of the source file on the system
    '''
    status_code = ReturnCodes.OK

    try:
        creds_file = os.path.join(
            CONFIG['CREDS']['CACHE'], username + '.keytab')
        if os.path.isfile(creds_file):
            os.remove(creds_file)
        gpg_decrypt_file(creds_file_encrypted, creds_file, CONFIG['CREDS']['GPG_BINARY_PATH'],
                         CONFIG['CREDS']['GPG_HOME'], CONFIG['CREDS']['GPG_PASSPHRASE_FILE'])
        os.chmod(creds_file, 0o0640)
        try:
            flavor = CONFIG['KRB_CLIENTS_FLAVOR']
        except KeyError:
            flavor = 'MIT'
        realms = krb_check_keytab(creds_file, flavor)
        # check if we can kinit with all realms found in the keytab
        for realm in realms:
            cachefile = "/tmp/krb5cc_"+username+"_"+realm
            krb_init_keytab(creds_file, username+'@'+realm, cachefile)
            os.unlink(cachefile)
        creds_file_encrypted_target = os.path.join(CONFIG['CREDS']['LOCATION'],
                                                   username + '.keytab.gpg')
        shutil.copyfile(creds_file_encrypted, creds_file_encrypted_target)
        os.chmod(creds_file_encrypted_target, 0o0600)

    except GPGError as error:
        sys.stderr.write(
            'File creds storage: GPG decryption failed. ' + str(error) + '\n')
        status_code = ReturnCodes.BACKEND_ERROR
    except KlistError as error:
        sys.stderr.write(
            'File creds storage: Kerberos keytab is not in a valid format. ' + str(error) + '\n')
        status_code = ReturnCodes.BAD_ARGS
    except KinitError as error:
        sys.stderr.write(
            'File creds storage: Kerberos keytab initialization failed. ' + str(error) + '\n')
        status_code = ReturnCodes.BAD_ARGS
    except shutil.Error:
        sys.stderr.write('Source and destination are the same files.' + '\n')
        status_code = ReturnCodes.BACKEND_ERROR
    except IOError as error:
        sys.stderr.write(
            'File creds storage: could not copy creds. ' + str(error) + '\n')
        status_code = ReturnCodes.BACKEND_ERROR

    return status_code


def main():
    """ parse arguments and run store the credentials"""
    parser = argparse.ArgumentParser(
        prog='get_creds', description='Acron credential getter.')
    parser.add_argument(
        '-v', '--version', action='version',
        version=pkg_resources.require('acron')[0].version)
    parser.add_argument('username', help='User to store the credentials for.')
    parser.add_argument('encrypted_creds_file',
                        help='Location of the encrypted creds file.')
    args = parser.parse_args()
    return store_creds(args.username, args.encrypted_creds_file)


if __name__ == "__main__":
    sys.exit(main())
